version: "3.9"
services:

  web:
    build: ./docker/node
    ports:
      - "3000:3000"
    networks:
      - frontend
    volumes:
      - type: bind
        source: ./app
        target: /usr/src/app
    working_dir: /usr/src/app
    tty: true

networks:
  frontend:
