import '../styles/globals.css';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import { css } from '@emotion/react';

import Header from '@/components/Header';

const main = css`
   & {
    flex: 1;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
  }
`;

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Docker Next.js</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <main css={main}>
        <Component {...pageProps} />
      </main>
    </>
  );
}
export default MyApp;
